//
// // -*- coding: utf-8, tab-width: 3 -*-

//                                                          _____                                           //
//                                                         (___  )                                          //
//                                            _   _  _   _   _/ /                                           //
//                                           | | | || | | | (  _)                                           //
//                                           | |_| || |_| | / /                                             //
//                                           | ._,_| \___/ /_/                                              //
//                                           | |                                                            //
//                                           |_|                                                            //

// mu7_cgemm.h
//
// Copyright (C) 2023 mu578. All rights reserved.
//

#include <mu7/mu7_reference/mu7_lsame.h>
#include <mu7/mu7_reference/mu7_operator.h>
#include <mu7/mu7_reference/mu7_xerbla.h>

#ifndef MU7_CGEMM_H
#define MU7_CGEMM_H 1

MU0_BEGIN_CDECL

//#!
//#! macro<_Tp>(
//#!   const char8  __transa
//#! , const char8  __transb
//#! , const sint   __m
//#! , const sint   __n
//#! , const sint   __k
//#! , const _Tp    __alpha
//#! , const _Tp &* __a
//#! , const sint   __lda
//#! , const _Tp &* __b
//#! , const sint   __ldb
//#! , const _Tp    __beta
//#! ,       _Tp &* __c
//#! , const sint   __ldc
//#! ) : void
//#!
#	define mu7_cgemm(_Tp, __transa, __transb, __m, __n, __k, __alpha, __a, __lda, __b, __ldb, __beta, __c, __ldc)                                                                                                                                                                                   \
mu0_scope_begin                                                                                                                                                                                                                                                                                    \
	const _Tp __mu7_cgemm__one__            = mu8_ini(_Tp, 1);                                                                                                                                                                                                                                      \
	const _Tp __mu7_cgemm__zero__           = mu8_ini(_Tp, 0);                                                                                                                                                                                                                                      \
	      _Tp __mu7_cgemm__temp__;                                                                                                                                                                                                                                                                  \
	                                                                                                                                                                                                                                                                                                \
	const mu0_sinteger __mu7_cgemm__m__     = mu0_const_sinteger(__m);                                                                                                                                                                                                                              \
	const mu0_sinteger __mu7_cgemm__n__     = mu0_const_sinteger(__n);                                                                                                                                                                                                                              \
	const mu0_sinteger __mu7_cgemm__n__     = mu0_const_sinteger(__k);                                                                                                                                                                                                                              \
	const mu0_sinteger __mu7_cgemm__lda__   = mu0_const_sinteger(__lda);                                                                                                                                                                                                                            \
	const mu0_sinteger __mu7_cgemm__ldb__   = mu0_const_sinteger(__ldb);                                                                                                                                                                                                                            \
	const mu0_sinteger __mu7_cgemm__ldc__   = mu0_const_sinteger(__ldc);                                                                                                                                                                                                                            \
	                                                                                                                                                                                                                                                                                                \
	const _Tp * __mu7_cgemm__a__            = mu0_const_cast(const _Tp *, __a);                                                                                                                                                                                                                     \
	const _Tp * __mu7_cgemm__b__            = mu0_const_cast(const _Tp *, __b);                                                                                                                                                                                                                     \
	      _Tp * __mu7_cgemm__c__            = mu0_cast(_Tp *, __c);                                                                                                                                                                                                                                 \
	                                                                                                                                                                                                                                                                                                \
	const _Tp __mu7_cgemm__alpha__          = __alpha;                                                                                                                                                                                                                                              \
	const _Tp __mu7_cgemm__beta__           = __beta;                                                                                                                                                                                                                                               \
	                                                                                                                                                                                                                                                                                                \
	      mu0_sinteger __mu7_cgemm__i__;                                                                                                                                                                                                                                                            \
	      mu0_sinteger __mu7_cgemm__info__;                                                                                                                                                                                                                                                         \
	      mu0_sinteger __mu7_cgemm__j__;                                                                                                                                                                                                                                                            \
	      mu0_sinteger __mu7_cgemm__l__;                                                                                                                                                                                                                                                            \
	      mu0_sinteger __mu7_cgemm__ncola__;                                                                                                                                                                                                                                                        \
	      mu0_sinteger __mu7_cgemm__nrowa__;                                                                                                                                                                                                                                                        \
	      mu0_sinteger __mu7_cgemm__nrowb__;                                                                                                                                                                                                                                                        \
	      mu0_sinteger __mu7_cgemm__ka__;                                                                                                                                                                                                                                                           \
	      mu0_sinteger __mu7_cgemm__kb__;                                                                                                                                                                                                                                                           \
	      mu0_sinteger __mu7_cgemm__conja__ = mu7_lsame(transa, 'C');                                                                                                                                                                                                                               \
	      mu0_sinteger __mu7_cgemm__conjb__ = mu7_lsame(transb, 'C');                                                                                                                                                                                                                               \
	      mu0_sinteger __mu7_cgemm__nota__  = mu7_lsame(transa, 'N');                                                                                                                                                                                                                               \
	      mu0_sinteger __mu7_cgemm__notb__  = mu7_lsame(transb, 'N');                                                                                                                                                                                                                               \
	                                                                                                                                                                                                                                                                                                \
	if (__mu7_cgemm__nota__) {                                                                                                                                                                                                                                                                      \
		__mu7_cgemm__ka__    = __mu7_cgemm__k__;                                                                                                                                                                                                                                                     \
		__mu7_cgemm__nrowa__ = __mu7_cgemm__m__;                                                                                                                                                                                                                                                     \
		__mu7_cgemm__ncola__ = __mu7_cgemm__k__;                                                                                                                                                                                                                                                     \
		mu7_unused(__mu7_cgemm__ka__);                                                                                                                                                                                                                                                               \
		mu7_unused(__mu7_cgemm__ncola__);                                                                                                                                                                                                                                                            \
	} else {                                                                                                                                                                                                                                                                                        \
		__mu7_cgemm__ka__    = __mu7_cgemm__m__;                                                                                                                                                                                                                                                     \
		__mu7_cgemm__nrowa__ = __mu7_cgemm__k__;                                                                                                                                                                                                                                                     \
		__mu7_cgemm__ncola__ = __mu7_cgemm__m__;                                                                                                                                                                                                                                                     \
		mu7_unused(__mu7_cgemm__ka__);                                                                                                                                                                                                                                                               \
		mu7_unused(__mu7_cgemm__ncola__);                                                                                                                                                                                                                                                            \
	}                                                                                                                                                                                                                                                                                               \
	if (__mu7_cgemm__notb__) {                                                                                                                                                                                                                                                                      \
		__mu7_cgemm__kb__    = __mu7_cgemm__n__;                                                                                                                                                                                                                                                     \
		__mu7_cgemm__nrowb__ = __mu7_cgemm__k__;                                                                                                                                                                                                                                                     \
		mu7_unused(__mu7_cgemm__kb__);                                                                                                                                                                                                                                                               \
	} else {                                                                                                                                                                                                                                                                                        \
		__mu7_cgemm__kb__    = __mu7_cgemm__k__;                                                                                                                                                                                                                                                     \
		__mu7_cgemm__nrowb__ = __mu7_cgemm__n__;                                                                                                                                                                                                                                                     \
		mu7_unused(__mu7_cgemm__kb__);                                                                                                                                                                                                                                                               \
	}                                                                                                                                                                                                                                                                                               \
	__mu7_cgemm__info__ = 0;                                                                                                                                                                                                                                                                        \
	if (!__mu7_cgemm__nota__ && !__mu7_cgemm__conja__ && !mu7_lsame(transa, 'T')) {                                                                                                                                                                                                                 \
		__mu7_cgemm__info__ = 1;                                                                                                                                                                                                                                                                     \
	} else if (!__mu7_cgemm__notb__ && !__mu7_cgemm__conjb__ && !mu7_lsame(transb, 'T')) {                                                                                                                                                                                                          \
		__mu7_cgemm__info__ = 2;                                                                                                                                                                                                                                                                     \
	} else if (__mu7_cgemm__m__ < 0) {                                                                                                                                                                                                                                                              \
		__mu7_cgemm__info__ = 3;                                                                                                                                                                                                                                                                     \
	} else if (__mu7_cgemm__n__ < 0) {                                                                                                                                                                                                                                                              \
		__mu7_cgemm__info__ = 4;                                                                                                                                                                                                                                                                     \
	} else if (__mu7_cgemm__k__ < 0) {                                                                                                                                                                                                                                                              \
		__mu7_cgemm__info__ = 5;                                                                                                                                                                                                                                                                     \
	} else if (lda < mu0_max(1, __mu7_cgemm__nrowa__)) {                                                                                                                                                                                                                                            \
		__mu7_cgemm__info__ = 8;                                                                                                                                                                                                                                                                     \
	} else if (ldb < mu0_max(1, __mu7_cgemm__nrowb__)) {                                                                                                                                                                                                                                            \
		__mu7_cgemm__info__ = 10;                                                                                                                                                                                                                                                                    \
	} else if (ldc < mu0_max(1, __mu7_cgemm__m__)) {                                                                                                                                                                                                                                                \
		__mu7_cgemm__info__ = 13;                                                                                                                                                                                                                                                                    \
	}                                                                                                                                                                                                                                                                                               \
	if (__mu7_cgemm__info__ != 0) {                                                                                                                                                                                                                                                                 \
		mu7_xerbla("CGEMM", __mu7_cgemm__info__);                                                                                                                                                                                                                                                    \
		goto __mu7_cgemm__exit__;                                                                                                                                                                                                                                                                    \
	}                                                                                                                                                                                                                                                                                               \
	if (__mu7_cgemm__m__ == 0 || __mu7_cgemm__n__ == 0 || ((mu8_alias_eq(_Tp, alpha, zero) || __mu7_cgemm__k__ == 0) && mu8_alias_eq(_Tp, beta, one))) {                                                                                                                                            \
		goto __mu7_cgemm__exit__;                                                                                                                                                                                                                                                                    \
	}                                                                                                                                                                                                                                                                                               \
	if (mu8_alias_eq(_Tp, alpha, zero)) {                                                                                                                                                                                                                                                           \
		if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                         \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                                 \
					__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = zero;                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		} else {                                                                                                                                                                                                                                                                                     \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                                 \
					__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__));                                                                                                    \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		}                                                                                                                                                                                                                                                                                            \
		goto __mu7_cgemm__exit__;                                                                                                                                                                                                                                                                    \
	}                                                                                                                                                                                                                                                                                               \
	if (__mu7_cgemm__notb__) {                                                                                                                                                                                                                                                                      \
		if (__mu7_cgemm__nota__) {                                                                                                                                                                                                                                                                   \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                   \
					for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                              \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = zero;                                                                                                                                                                                                \
					}                                                                                                                                                                                                                                                                                   \
				} else if (!mu8_alias_eq(_Tp, beta, one)) {                                                                                                                                                                                                                                            \
					for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                              \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__));                                                                                                 \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
				for (__mu7_cgemm__l__ = 1; __mu7_cgemm__l__ <= __mu7_cgemm__k__; ++__mu7_cgemm__l__) {                                                                                                                                                                                                 \
					temp = mu8_alias_mul(_Tp, alpha, __mu7_mat__(b, ldb, __mu7_cgemm__kb__, __mu7_cgemm__l__, __mu7_cgemm__j__));                                                                                                                                                                       \
					for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                              \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_add(_Tp, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__), mu8_alias_mul(_Tp, temp, __mu7_mat__(a, lda, __mu7_cgemm__ka__, __mu7_cgemm__i__, __mu7_cgemm__l__))); \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		} else if (__mu7_cgemm__conja__) {                                                                                                                                                                                                                                                           \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                                 \
					temp = zero;                                                                                                                                                                                                                                                                        \
					for (__mu7_cgemm__l__ = 1; __mu7_cgemm__l__ <= __mu7_cgemm__k__; ++__mu7_cgemm__l__) {                                                                                                                                                                                              \
						temp = mu8_alias_add(_Tp, temp, mu8_alias_mul(_Tp, mu8_alias_conj(_Tp, __mu7_mat__(a, lda, __mu7_cgemm__ka__, __mu7_cgemm__l__, __mu7_cgemm__i__)), __mu7_mat__(b, ldb, __mu7_cgemm__kb__, __mu7_cgemm__l__, __mu7_cgemm__j__)));                                                \
					}                                                                                                                                                                                                                                                                                   \
					if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, alpha, temp);                                                                                                                                                                     \
					} else {                                                                                                                                                                                                                                                                            \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_add(_Tp, mu8_alias_mul(_Tp, alpha, temp), mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__)));                                            \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		} else {                                                                                                                                                                                                                                                                                     \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                                 \
					temp = zero;                                                                                                                                                                                                                                                                        \
					for (__mu7_cgemm__l__ = 1; __mu7_cgemm__l__ <= __mu7_cgemm__k__; ++__mu7_cgemm__l__) {                                                                                                                                                                                              \
						temp = mu8_alias_add(_Tp, temp, mu8_alias_mul(_Tp, __mu7_mat__(a, lda, __mu7_cgemm__ka__, __mu7_cgemm__l__, __mu7_cgemm__i__), __mu7_mat__(b, ldb, __mu7_cgemm__kb__, __mu7_cgemm__l__, __mu7_cgemm__j__)));                                                                     \
					}                                                                                                                                                                                                                                                                                   \
					if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, alpha, temp);                                                                                                                                                                     \
					} else {                                                                                                                                                                                                                                                                            \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_add(_Tp, mu8_alias_mul(_Tp, alpha, temp), mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__)));                                            \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		}                                                                                                                                                                                                                                                                                            \
	} else if (__mu7_cgemm__nota__) {                                                                                                                                                                                                                                                               \
		if (__mu7_cgemm__conjb__) {                                                                                                                                                                                                                                                                  \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                   \
					for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                              \
						 __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = zero;                                                                                                                                                                                               \
					}                                                                                                                                                                                                                                                                                   \
				} else if (!mu8_alias_eq(_Tp, beta, one)) {                                                                                                                                                                                                                                            \
					for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                              \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__));                                                                                                 \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
				for (__mu7_cgemm__l__ = 1; __mu7_cgemm__l__ <= __mu7_cgemm__k__; ++__mu7_cgemm__l__) {                                                                                                                                                                                                 \
					temp = mu8_alias_mul(_Tp, alpha, mu8_alias_conj(_Tp, __mu7_mat__(b, ldb, __mu7_cgemm__kb__, __mu7_cgemm__j__, __mu7_cgemm__l__)));                                                                                                                                                  \
					for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                              \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_add(_Tp, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__), mu8_alias_mul(_Tp, temp, __mu7_mat__(a, lda, __mu7_cgemm__ka__, __mu7_cgemm__i__, __mu7_cgemm__l__))); \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		} else {                                                                                                                                                                                                                                                                                     \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                   \
					for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                              \
						 __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = zero;                                                                                                                                                                                               \
					}                                                                                                                                                                                                                                                                                   \
				} else if (!mu8_alias_eq(_Tp, beta, one)) {                                                                                                                                                                                                                                            \
					for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                              \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__));                                                                                                 \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
				for (__mu7_cgemm__l__ = 1; __mu7_cgemm__l__ <= __mu7_cgemm__k__; ++__mu7_cgemm__l__) {                                                                                                                                                                                                 \
					temp = mu8_alias_mul(_Tp, alpha, __mu7_mat__(b, ldb, __mu7_cgemm__kb__, __mu7_cgemm__j__, __mu7_cgemm__l__));                                                                                                                                                                       \
					for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                              \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_add(_Tp, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__), mu8_alias_mul(_Tp, temp, __mu7_mat__(a, lda, __mu7_cgemm__ka__, __mu7_cgemm__i__, __mu7_cgemm__l__))); \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		}                                                                                                                                                                                                                                                                                            \
	} else if (__mu7_cgemm__conja__) {                                                                                                                                                                                                                                                              \
		if (__mu7_cgemm__conjb__) {                                                                                                                                                                                                                                                                  \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                                 \
					temp = zero;                                                                                                                                                                                                                                                                        \
					for (__mu7_cgemm__l__ = 1; __mu7_cgemm__l__ <= __mu7_cgemm__k__; ++__mu7_cgemm__l__) {                                                                                                                                                                                              \
						temp = mu8_alias_add(_Tp, temp, mu8_alias_mul(_Tp, mu8_alias_conj(_Tp, __mu7_mat__(a, lda, __mu7_cgemm__ka__, __mu7_cgemm__l__, __mu7_cgemm__i__)), mu8_alias_conj(_Tp, __mu7_mat__(b, ldb, __mu7_cgemm__kb__, __mu7_cgemm__j__, __mu7_cgemm__l__))));                           \
					}                                                                                                                                                                                                                                                                                   \
					if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, alpha, temp);                                                                                                                                                                     \
					} else {                                                                                                                                                                                                                                                                            \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_add(_Tp, mu8_alias_mul(_Tp, alpha, temp), mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__)));                                            \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		} else {                                                                                                                                                                                                                                                                                     \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                                 \
					temp = zero;                                                                                                                                                                                                                                                                        \
					for (__mu7_cgemm__l__ = 1; __mu7_cgemm__l__ <= __mu7_cgemm__k__; ++__mu7_cgemm__l__) {                                                                                                                                                                                              \
						temp = mu8_alias_add(_Tp, temp, mu8_alias_mul(_Tp, mu8_alias_conj(_Tp, __mu7_mat__(a, lda, __mu7_cgemm__ka__, __mu7_cgemm__l__, __mu7_cgemm__i__)), __mu7_mat__(b, ldb, __mu7_cgemm__kb__, __mu7_cgemm__j__, __mu7_cgemm__l__)));                                                \
					}                                                                                                                                                                                                                                                                                   \
					if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, alpha, temp);                                                                                                                                                                     \
					} else {                                                                                                                                                                                                                                                                            \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_add(_Tp, mu8_alias_mul(_Tp, alpha, temp), mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__)));                                            \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		}                                                                                                                                                                                                                                                                                            \
	} else {                                                                                                                                                                                                                                                                                        \
		if (__mu7_cgemm__conjb__) {                                                                                                                                                                                                                                                                  \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                                 \
					temp = zero;                                                                                                                                                                                                                                                                        \
					for (__mu7_cgemm__l__ = 1; __mu7_cgemm__l__ <= __mu7_cgemm__k__; ++__mu7_cgemm__l__) {                                                                                                                                                                                              \
						temp = mu8_alias_add(_Tp, temp, mu8_alias_mul(_Tp, __mu7_mat__(a, lda, __mu7_cgemm__ka__, __mu7_cgemm__l__, __mu7_cgemm__i__), mu8_alias_conj(_Tp, __mu7_mat__(b, ldb, __mu7_cgemm__kb__, __mu7_cgemm__j__, __mu7_cgemm__l__))));                                                \
					}                                                                                                                                                                                                                                                                                   \
					if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, alpha, temp);                                                                                                                                                                     \
					} else {                                                                                                                                                                                                                                                                            \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_add(_Tp, mu8_alias_mul(_Tp, alpha, temp), mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__)));                                            \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		} else {                                                                                                                                                                                                                                                                                     \
			for (__mu7_cgemm__j__ = 1; __mu7_cgemm__j__ <= __mu7_cgemm__n__; ++__mu7_cgemm__j__) {                                                                                                                                                                                                    \
				for (__mu7_cgemm__i__ = 1; __mu7_cgemm__i__ <= __mu7_cgemm__m__; ++__mu7_cgemm__i__) {                                                                                                                                                                                                 \
					temp = zero;                                                                                                                                                                                                                                                                        \
					for (__mu7_cgemm__l__ = 1; __mu7_cgemm__l__ <= __mu7_cgemm__k__; ++__mu7_cgemm__l__) {                                                                                                                                                                                              \
						temp = mu8_alias_add(_Tp, temp, mu8_alias_mul(_Tp, __mu7_mat__(a, lda, __mu7_cgemm__ka__, __mu7_cgemm__l__, __mu7_cgemm__i__), __mu7_mat__(b, ldb, __mu7_cgemm__kb__, __mu7_cgemm__j__, __mu7_cgemm__l__)));                                                                     \
					}                                                                                                                                                                                                                                                                                   \
					if (mu8_alias_eq(_Tp, beta, zero)) {                                                                                                                                                                                                                                                \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_mul(_Tp, alpha, temp);                                                                                                                                                                     \
					} else {                                                                                                                                                                                                                                                                            \
						__mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__) = mu8_alias_add(_Tp, mu8_alias_mul(_Tp, alpha, temp), mu8_alias_mul(_Tp, beta, __mu7_mat__(c, ldc, __mu7_cgemm__n__, __mu7_cgemm__i__, __mu7_cgemm__j__)));                                            \
					}                                                                                                                                                                                                                                                                                   \
				}                                                                                                                                                                                                                                                                                      \
			}                                                                                                                                                                                                                                                                                         \
		}                                                                                                                                                                                                                                                                                            \
	}                                                                                                                                                                                                                                                                                               \
	__mu7_cgemm__exit__:;                                                                                                                                                                                                                                                                           \
mu0_scope_end

MU0_END_CDECL

#endif /* !MU7_CGEMM_H */

/* EOF */